defmodule CanOpener.Client do
  @moduledoc """
  Generic HTTP client for OpenAPI-generated APIs.

  Created via the `client/1` function generated by `use CanOpener`.
  """

  @type auth :: {:bearer, String.t()} | {:header, String.t(), String.t()} | nil

  @type t :: %__MODULE__{
          base_url: String.t(),
          auth: auth(),
          req_options: keyword()
        }

  defstruct [:base_url, :auth, req_options: []]

  @doc """
  Build a new client struct from OTP app config and explicit options.

  Called by the generated `client/1` function — not intended for direct use.
  """
  def new(otp_app, default_base_url, auth_strategy, opts) do
    base_url =
      Keyword.get(opts, :base_url) ||
        Application.get_env(otp_app, :base_url, default_base_url)

    api_key =
      Keyword.get(opts, :api_key) ||
        Application.get_env(otp_app, :api_key)

    auth = build_auth(auth_strategy, api_key)

    %__MODULE__{
      base_url: base_url,
      auth: auth,
      req_options: Keyword.get(opts, :req_options, [])
    }
  end

  defp build_auth(_strategy, nil), do: nil
  defp build_auth(:bearer, key), do: {:bearer, key}
  defp build_auth({:header, header_name}, key), do: {:header, header_name, key}
  defp build_auth(:none, _key), do: nil

  @doc """
  Execute an HTTP request against the API.

  Called by generated operation functions — not intended for direct use.
  """
  def request(%__MODULE__{} = client, method, path, opts \\ []) do
    headers = auth_headers(client.auth)

    req_opts =
      [method: method, url: client.base_url <> path, headers: headers]
      |> Keyword.merge(opts)
      |> Keyword.merge(client.req_options)

    case Req.request(req_opts) do
      {:ok, %Req.Response{status: status, body: body}} when status in 200..299 ->
        {:ok, body}

      {:ok, %Req.Response{status: status, body: body}} ->
        {:error, %{status: status, body: body}}

      {:error, exception} ->
        {:error, exception}
    end
  end

  defp auth_headers(nil), do: []
  defp auth_headers({:bearer, token}), do: [{"authorization", "Bearer #{token}"}]
  defp auth_headers({:header, name, value}), do: [{name, value}]
end
